use_frameworks!

platform :ios, '12.0'

target 'HSPAnalytics_Example' do
  pod 'HSPAnalytics', :path => '../'

  target 'HSPAnalytics_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
